import "./src/styles/global.css"
import "@fontsource/damion"
import "@fontsource/fira-mono"
import "@fontsource/jost"
import "@fontsource/mouse-memoirs"
import "@fontsource/nova-cut"
import "@fontsource/roboto"
import "@fontsource/rubik-dirt"
import "@fontsource/ubuntu"
import "@fontsource/urbanist"
import "@fontsource/viga"
import wrapWithProvider from "./wrap-with-provider"
export const wrapRootElement = wrapWithProvider
